# Generated by Django 4.2.16 on 2024-12-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.DurationField()),
                ('file_path', models.FilePathField(match='.*\\.mp3$', path='media/music/', recursive=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
