# Generated by Django 4.2.16 on 2024-12-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='albumImage',
            field=models.ImageField(blank=True, null=True, upload_to='music data/album covers/'),
        ),
    ]
