# Generated by Django 4.2.16 on 2024-12-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_song_albumimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics_path',
            field=models.FilePathField(blank=True, match='.*\\.txt$', null=True, path='media/music data/lyrics/', recursive=True),
        ),
    ]
