# Generated by Django 4.2.16 on 2024-12-31 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_song_lyrics_path'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('title', 'artist')},
        ),
    ]
